import typescriptEslint from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import importPlugin from 'eslint-plugin-import';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';

export default [
    {
        ignores: ['node_modules/**', 'dist/**', 'playwright/**', 'coverage/**', 'coverage-ct/**', 'src/manifest.ts'],
    },
    {
        files: ['**/*.{js,jsx,ts,tsx}'],
        languageOptions: {
            parser: typescriptParser,
            parserOptions: {
                ecmaVersion: 2017,
                sourceType: 'module',
                ecmaFeatures: {
                    jsx: true,
                    impliedStrict: true,
                    modules: true,
                },
            },
            globals: {
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                HTMLElement: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLTextAreaElement: 'readonly',
                HTMLSelectElement: 'readonly',
                HTMLDivElement: 'readonly',
                HTMLButtonElement: 'readonly',
                HTMLFormElement: 'readonly',
                HTMLAnchorElement: 'readonly',
                Event: 'readonly',
                MouseEvent: 'readonly',
                KeyboardEvent: 'readonly',
                FormData: 'readonly',
                Promise: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Symbol: 'readonly',
                globalThis: 'readonly',
                module: 'readonly',
                require: 'readonly',
                process: 'readonly',
                __dirname: 'readonly',
                RequestInit: 'readonly',
                Response: 'readonly',
                AbortController: 'readonly',
            },
        },
        plugins: {
            '@typescript-eslint': typescriptEslint,
            'import': importPlugin,
            'react': reactPlugin,
            'react-hooks': reactHooksPlugin,
        },
        settings: {
            react: {
                pragma: 'React',
                version: 'detect',
            },
        },
        rules: {
            // TypeScript rules
            '@typescript-eslint/array-type': ['error', {default: 'array-simple'}],
            '@typescript-eslint/consistent-type-imports': ['error', {disallowTypeAnnotations: false}],
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/naming-convention': [
                'error',
                {selector: 'function', format: ['camelCase', 'PascalCase']},
                {selector: 'variable', format: ['camelCase', 'PascalCase', 'UPPER_CASE']},
                {selector: 'parameter', format: ['camelCase', 'PascalCase'], leadingUnderscore: 'allow'},
                {selector: 'typeLike', format: ['PascalCase']},
            ],
            '@typescript-eslint/no-dupe-class-members': 'error',
            '@typescript-eslint/no-empty-function': 'off',
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-unused-vars': ['error', {vars: 'all', args: 'after-used'}],
            '@typescript-eslint/no-use-before-define': ['error', {classes: false, functions: false, variables: false}],
            '@typescript-eslint/no-var-requires': 'off',

            // Import rules
            'import/no-duplicates': 'error',
            'import/no-unresolved': 'off',
            'import/order': [
                'error',
                {
                    'newlines-between': 'always',
                    'groups': ['builtin', 'external', 'internal', 'sibling', 'parent', 'index'],
                    'pathGroups': [
                        {pattern: '@mattermost/**', group: 'external', position: 'after'},
                        {pattern: 'mattermost-redux/**', group: 'external', position: 'after'},
                        {pattern: '@(selectors|actions|stores|store|reducers){,/**}', group: 'external', position: 'after'},
                        {pattern: 'components/**', group: 'external', position: 'after'},
                        {pattern: 'types{,/**}', group: 'internal', position: 'after'},
                    ],
                    'alphabetize': {order: 'asc', caseInsensitive: true},
                    'distinctGroup': true,
                    'pathGroupsExcludedImportTypes': ['builtin'],
                },
            ],

            // React rules
            'react/display-name': ['off', {ignoreTranspilerName: false}],
            'react/forbid-component-props': 'off',
            'react/forbid-elements': ['error', {forbid: ['embed']}],
            'react/jsx-boolean-value': ['error', 'always'],
            'react/jsx-closing-bracket-location': ['error', {location: 'tag-aligned'}],
            'react/jsx-curly-spacing': ['error', 'never'],
            'react/jsx-equals-spacing': ['error', 'never'],
            'react/jsx-filename-extension': ['error', {extensions: ['.jsx', '.tsx']}],
            'react/jsx-first-prop-new-line': ['error', 'multiline'],
            'react/jsx-handler-names': 'off',
            'react/jsx-indent': ['error', 4],
            'react/jsx-indent-props': ['error', 4],
            'react/jsx-key': 'error',
            'react/jsx-max-props-per-line': ['error', {maximum: 1}],
            'react/jsx-no-bind': 'off',
            'react/jsx-no-comment-textnodes': 'error',
            'react/jsx-no-duplicate-props': ['error', {ignoreCase: false}],
            'react/jsx-no-literals': 'error',
            'react/jsx-no-target-blank': 'error',
            'react/jsx-no-undef': 'error',
            'react/jsx-pascal-case': 'error',
            'react/jsx-tag-spacing': ['error', {closingSlash: 'never', beforeSelfClosing: 'never', afterOpening: 'never'}],
            'react/jsx-uses-react': 'error',
            'react/jsx-uses-vars': 'error',
            'react/jsx-wrap-multilines': 'error',
            'react/no-array-index-key': 'warn',
            'react/no-children-prop': 'error',
            'react/no-danger': 'off',
            'react/no-danger-with-children': 'error',
            'react/no-deprecated': 'warn',
            'react/no-did-mount-set-state': 'error',
            'react/no-did-update-set-state': 'error',
            'react/no-direct-mutation-state': 'error',
            'react/no-find-dom-node': 'warn',
            'react/no-is-mounted': 'error',
            'react/no-multi-comp': ['error', {ignoreStateless: true}],
            'react/no-render-return-value': 'error',
            'react/no-set-state': 'off',
            'react/no-string-refs': 'error',
            'react/no-unescaped-entities': 'error',
            'react/no-unknown-property': 'error',
            'react/no-unused-prop-types': ['warn', {skipShapeProps: true}],
            'react/prefer-es6-class': 'error',
            'react/prefer-stateless-function': 'off',
            'react/prop-types': 'error',
            'react/require-default-props': 'off',
            'react/require-optimization': 'warn',
            'react/require-render-return': 'error',
            'react/self-closing-comp': 'error',
            'react/sort-comp': 'off',
            'react/style-prop-object': 'error',

            // React Hooks rules
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'warn',

            // Core ESLint rules
            'array-bracket-spacing': ['error', 'never'],
            'array-callback-return': 'error',
            'arrow-body-style': 'off',
            'arrow-parens': ['error', 'always'],
            'arrow-spacing': ['error', {before: true, after: true}],
            'block-scoped-var': 'error',
            'brace-style': ['error', '1tbs', {allowSingleLine: false}],
            'camelcase': 'off',
            'capitalized-comments': 'off',
            'class-methods-use-this': 'off',
            'comma-dangle': ['error', 'always-multiline'],
            'comma-spacing': ['error', {before: false, after: true}],
            'comma-style': ['error', 'last'],
            'complexity': ['off', 10],
            'computed-property-spacing': ['error', 'never'],
            'consistent-return': 'error',
            'consistent-this': ['error', 'self'],
            'constructor-super': 'error',
            'curly': ['error', 'all'],
            'dot-location': ['error', 'object'],
            'dot-notation': 'error',
            'eol-last': ['error', 'always'],
            'eqeqeq': ['error', 'smart'],
            'func-call-spacing': ['error', 'never'],
            'func-name-matching': 'off',
            'func-names': 'error',
            'func-style': ['error', 'declaration', {allowArrowFunctions: true}],
            'generator-star-spacing': ['error', {before: false, after: true}],
            'guard-for-in': 'error',
            'indent': 'off',
            'jsx-quotes': ['error', 'prefer-single'],
            'key-spacing': ['error', {beforeColon: false, afterColon: true, mode: 'strict'}],
            'keyword-spacing': ['error', {before: true, after: true, overrides: {}}],
            'line-comment-position': 'off',
            'linebreak-style': 'error',
            'lines-around-comment': ['error', {beforeBlockComment: true, beforeLineComment: true, allowBlockStart: true, allowBlockEnd: true}],
            'max-lines': ['warn', {max: 800, skipBlankLines: true, skipComments: false}],
            'max-nested-callbacks': ['error', 10],
            'max-statements-per-line': ['error', {max: 1}],
            'multiline-ternary': ['warn', 'never'],
            'new-cap': 'error',
            'new-parens': 'error',
            'newline-before-return': 'off',
            'newline-per-chained-call': 'off',
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-await-in-loop': 'error',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': ['error', 'except-parens'],
            'no-confusing-arrow': 'error',
            'no-console': 'error',
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': 'error',
            'no-debugger': 'error',
            'no-div-regex': 'error',
            'no-dupe-args': 'error',
            'no-dupe-class-members': 'off',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-duplicate-imports': 'off',
            'no-else-return': 'error',
            'no-empty': 'error',
            'no-empty-function': 'off',
            'no-empty-pattern': 'error',
            'no-eval': 'error',
            'no-ex-assign': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-label': 'error',
            'no-extra-parens': 'off',
            'no-extra-semi': 'error',
            'no-fallthrough': 'error',
            'no-floating-decimal': 'error',
            'no-func-assign': 'error',
            'no-global-assign': 'error',
            'no-implicit-coercion': 'error',
            'no-implicit-globals': 'off',
            'no-implied-eval': 'error',
            'no-inner-declarations': 'off',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-magic-numbers': 'off',
            'no-mixed-operators': ['error', {allowSamePrecedence: false}],
            'no-mixed-spaces-and-tabs': 'error',
            'no-multi-assign': 'error',
            'no-multi-spaces': ['error', {exceptions: {Property: false}}],
            'no-multi-str': 'off',
            'no-multiple-empty-lines': ['error', {max: 1}],
            'no-negated-condition': 'error',
            'no-nested-ternary': 'error',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'error',
            'no-process-env': 'error',
            'no-proto': 'error',
            'no-prototype-builtins': 'warn',
            'no-restricted-imports': [
                'error',
                {
                    patterns: [
                        {group: ['@mattermost/compass-components/*'], message: 'compass-components is now archived.'},
                    ],
                    paths: [
                        {name: 'react-bootstrap', importNames: ['OverlayTrigger'], message: "Use OverlayTrigger from '/components/overlay_trigger' instead."},
                        {name: 'redux', importNames: ['DeepPartial'], message: "Use DeepPartial from '@mattermost/types/utilities' instead."},
                        {name: 'lodash', message: 'Import individual functions from lodash/<function> instead.'},
                    ],
                },
            ],
            'no-return-assign': ['error', 'always'],
            'no-script-url': 'error',
            'no-self-assign': ['error', {props: true}],
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-shadow': 'off',
            'no-shadow-restricted-names': 'error',
            'no-tabs': 'off',
            'no-template-curly-in-string': 'error',
            'no-ternary': 'off',
            'no-this-before-super': 'error',
            'no-throw-literal': 'error',
            'no-trailing-spaces': ['error', {skipBlankLines: false}],
            'no-undef-init': 'error',
            'no-undefined': 'off',
            'no-underscore-dangle': 'error',
            'no-unexpected-multiline': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unneeded-ternary': ['error', {defaultAssignment: false}],
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unused-expressions': 'error',
            'no-unused-vars': 'off',
            'no-use-before-define': 'off',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-constructor': 'error',
            'no-useless-escape': 'error',
            'no-useless-rename': 'error',
            'no-useless-return': 'error',
            'no-var': 'off',
            'no-void': 'error',
            'no-warning-comments': 'warn',
            'no-whitespace-before-property': 'error',
            'no-with': 'error',
            'object-curly-newline': 'off',
            'object-curly-spacing': ['error', 'never'],
            'object-property-newline': ['error', {allowMultiplePropertiesPerLine: true}],
            'object-shorthand': ['error', 'always'],
            'one-var': ['error', 'never'],
            'one-var-declaration-per-line': 'off',
            'operator-assignment': ['error', 'always'],
            'operator-linebreak': ['error', 'after'],
            'padded-blocks': ['error', 'never'],
            'prefer-arrow-callback': 'error',
            'prefer-const': 'error',
            'prefer-destructuring': 'off',
            'prefer-numeric-literals': 'error',
            'prefer-promise-reject-errors': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'off',
            'quote-props': ['error', 'as-needed'],
            'quotes': ['error', 'single', 'avoid-escape'],
            'radix': 'error',
            'require-yield': 'error',
            'rest-spread-spacing': ['error', 'never'],
            'semi': ['error', 'always'],
            'semi-spacing': ['error', {before: false, after: true}],
            'sort-imports': 'off',
            'sort-keys': 'off',
            'space-before-blocks': ['error', 'always'],
            'space-before-function-paren': ['error', {anonymous: 'never', named: 'never', asyncArrow: 'always'}],
            'space-in-parens': ['error', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': ['error', {words: true, nonwords: false}],
            'symbol-description': 'error',
            'template-curly-spacing': ['error', 'never'],
            'valid-typeof': ['error', {requireStringLiterals: false}],
            'vars-on-top': 'off',
            'wrap-iife': ['error', 'outside'],
            'wrap-regex': 'error',
            'yoda': ['error', 'never', {exceptRange: false, onlyEquality: false}],
        },
    },

    // Relaxed rules for test files
    {
        files: ['**/*.test.*', '**/*.spec.*', '**/*.pw.*', '**/tests/**'],
        rules: {
            'no-underscore-dangle': 'off',
            'func-names': 'off',
            'no-process-env': 'off',
            'max-lines': 'off',
            'react/prop-types': 'off',
            'react/require-optimization': 'off',
        },
    },

    // Relaxed rules for config files (webpack, playwright, eslint, babel)
    {
        files: ['*.js', '*.mjs', '*.config.*'],
        rules: {
            'no-process-env': 'off',
            'no-console': 'off',
            '@typescript-eslint/naming-convention': 'off',
            'func-names': 'off',
            'no-underscore-dangle': 'off',
        },
    },
];
